<Project>
  <PropertyGroup>
    <BaseOutputPath>$(MSBuildThisFileDirectory)../bin/</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)../bin/objs/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
    <IntermediateOutputPath>$(MSBuildThisFileDirectory)../bin/objs/$(Configuration)/$(MSBuildProjectName)/</IntermediateOutputPath>
    <DebugType>pdbonly</DebugType>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>
</Project>
