name: CI-Pipeline

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
   build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]
    env:
      VS_VERSION: "2022"
      SLNX_FILE_IGN: IGN.sln
      PREMAKE_VERSION: 5.0.0-beta8

    steps:
      - name: Checkout repository recursively (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Run Generate Script
        shell: pwsh
        run: ./gen.bat

      - name: Resore NuGet packages
        shell: pwsh
        run: msbuild $env:SLNX_FILE_IGN /t:Restore /p:Configuration=${{ matrix.configuration }} /p:Platform="x64"

      - name: Build Visual Studio
        shell: pwsh
        run: msbuild $env:SLNX_FILE_IGN /t:Rebuild /p:Configuration=${{ matrix.configuration }} /p:Platform="x64"
